# TASK 1  :  DATA CLEANING & PREPROCESSING

# 🍽️ Restaurant Sales Data — Cleaning & Preprocessing

### CODSOFT Internship — Task 1

**Project:** Restaurant Sales Data Cleaning and Preprocessing  
**Tools:** Python | Pandas | NumPy | Jupyter Notebook

---

## 📌 Project Overview

This project focuses on cleaning and preprocessing a restaurant sales dataset using Python and Pandas.

The main objective is to identify and handle data quality issues such as:

- Missing values
- Duplicate records
- Inconsistent data entries
- Incorrect data types
- Unnecessary spaces and formatting issues

The cleaned dataset will be prepared for further **Data Analysis and Visualization**.

## Import a dataset using Python and inspect its structure.

In [1]:
import pandas as pd
import numpy as np

# Load dataset
data = pd.read_csv("../data/raw/restaurant_sales_data.csv")
data

,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,ORD_705844,CUST_092,Side Dishes,Side Salad,3.0,1.0,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,ORD_630508,CUST_075,Drinks,NaN,NaN,2.0,5.0,2022-08-09,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash
...,...,...,...,...,...,...,...,...,...
17529,ORD_320102,CUST_021,Drinks,NaN,NaN,4.0,4.0,2023-12-23,Cash
17530,ORD_974128,CUST_069,Desserts,Ice Cream,5.0,3.0,15.0,2023-12-18,Cash
17531,ORD_108324,CUST_050,Desserts,Ice Cream,5.0,4.0,20.0,2022-05-20,Digital Wallet
17532,ORD_612647,CUST_073,Side Dishes,Mashed Potatoes,4.0,2.0,8.0,2022-01-27,Digital Wallet
17533,ORD_680707,CUST_006,Desserts,NaN,7.0,4.0,28.0,2023-01-07,NaN

In [2]:
# Display first 5 rows
data.head()

,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,ORD_705844,CUST_092,Side Dishes,Side Salad,3.0,1.0,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,ORD_630508,CUST_075,Drinks,NaN,NaN,2.0,5.0,2022-08-09,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash

In [3]:
# Display last 5 rows
data.tail()

,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
17529,ORD_320102,CUST_021,Drinks,NaN,NaN,4.0,4.0,2023-12-23,Cash
17530,ORD_974128,CUST_069,Desserts,Ice Cream,5.0,3.0,15.0,2023-12-18,Cash
17531,ORD_108324,CUST_050,Desserts,Ice Cream,5.0,4.0,20.0,2022-05-20,Digital Wallet
17532,ORD_612647,CUST_073,Side Dishes,Mashed Potatoes,4.0,2.0,8.0,2022-01-27,Digital Wallet
17533,ORD_680707,CUST_006,Desserts,NaN,7.0,4.0,28.0,2023-01-07,NaN

In [4]:
# Check dataset shape
print("Number of Rows:", data.shape[0])
print("Number of Columns:", data.shape[1])
print("Dataset Shape:", data.shape)

Number of Rows: 17534
Number of Columns: 9
Dataset Shape: (17534, 9)

In [5]:
# Display column names
print("Column Names:")
print(data.columns)

Column Names:
Index(['Order ID', 'Customer ID', 'Category', 'Item', 'Price', 'Quantity',
       'Order Total', 'Order Date', 'Payment Method'],
      dtype='object')

In [6]:
# Inspect dataset structure
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17534 entries, 0 to 17533
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        17534 non-null  object
 1   Customer ID     17534 non-null  object
 2   Category        17534 non-null  object
 3   Item            15776 non-null  object
 4   Price           16658 non-null  float64
 5   Quantity        17104 non-null  float64
 6   Order Total     17104 non-null  float64
 7   Order Date      17534 non-null  object
 8   Payment Method  16452 non-null  object
dtypes: float64(3), object(6)
memory usage: 1.2+ MB

In [7]:
# Statistical summary
data.describe(include="all")

,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
count,17534,17534,17534,15776,16658.000000,17104.000000,17104.000000,17534,16452
unique,17534,100,5,26,NaN,NaN,NaN,730,3
top,ORD_705844,CUST_066,Main Dishes,Pasta Alfredo,NaN,NaN,NaN,2023-11-25,Credit Card
freq,1,207,3551,998,NaN,NaN,NaN,42,5504
mean,NaN,NaN,NaN,NaN,6.586325,3.014149,19.914494,NaN,NaN
std,NaN,NaN,NaN,NaN,4.834652,1.414598,18.732549,NaN,NaN
min,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,3.000000,2.000000,7.500000,NaN,NaN
50%,NaN,NaN,NaN,NaN,5.000000,3.000000,15.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,7.000000,4.000000,25.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,20.000000,5.000000,100.000000,NaN,NaN

In [8]:
# Check data types
print("Data Types:")
print(data.dtypes)

Data Types:
Order ID           object
Customer ID        object
Category           object
Item               object
Price             float64
Quantity          float64
Order Total       float64
Order Date         object
Payment Method     object
dtype: object

## Identify missing values, duplicate records, and inconsistent data entries.

In [9]:
# Check missing values
print("Missing Values:")
print(data.isnull().sum())

Missing Values:
Order ID             0
Customer ID          0
Category             0
Item              1758
Price              876
Quantity           430
Order Total        430
Order Date           0
Payment Method    1082
dtype: int64

In [10]:
# Calculate missing value percentage
missing_percentage = (data.isnull().sum() / len(data)) * 100
missing_summary = pd.DataFrame({
    "Missing Values": data.isnull().sum(),
    "Missing Percentage": missing_percentage
})

missing_summary = missing_summary[
    missing_summary["Missing Values"] > 0
]

missing_summary

                Missing Values  Missing Percentage
Item                      1758           10.026235
Price                      876            4.996008
Quantity                   430            2.452378
Order Total                430            2.452378
Payment Method            1082            6.170868

In [11]:
# Count duplicate records

duplicate_count = data.duplicated().sum()
print("Number of duplicate records:", duplicate_count)

Number of duplicate records: 0

In [12]:
# Display duplicate records

duplicates = data[data.duplicated(keep=False)]
duplicates.head(10)

Empty DataFrame
Columns: [Order ID, Customer ID, Category, Item, Price, Quantity, Order Total, Order Date, Payment Method]
Index: []

In [13]:
# Check unique Category values

print("Category Values:")
print(data["Category"].value_counts(dropna=False))

Category Values:
Category
Main Dishes    3551
Starters       3527
Desserts       3496
Drinks         3488
Side Dishes    3472
Name: count, dtype: int64

In [14]:
# Check unique Item values

print("Item Values:")
print(data["Item"].value_counts(dropna=False))

Item Values:
Item
NaN                   1758
Pasta Alfredo          998
Side Salad             978
Water                  956
Ice Cream              936
French Fries           897
Grilled Chicken        822
Mashed Potatoes        799
Chocolate Cake         798
Coca Cola              756
Cheese Fries           686
Orange Juice           591
Grilled Vegetables     578
Steak                  574
Cheesecake             485
Lemonade               479
Sweet Potato Fries     471
Beef Chili             470
Brownie                469
Fruit Salad            449
Chicken Melt           442
Salmon                 422
Garlic Bread           399
Vegetarian Platter     382
Onion Rings            373
Iced Tea               328
Nachos Grande          238
Name: count, dtype: int64

In [15]:
# Check Payment Method values

print("Payment Method Values:")
print(data["Payment Method"].value_counts(dropna=False))

Payment Method Values:
Payment Method
Credit Card       5504
Cash              5499
Digital Wallet    5449
NaN               1082
Name: count, dtype: int64

## Clean the dataset by handling null values, removing duplicates, and correcting data types.

In [16]:
# Create a copy for cleaning

cleaned_data = data.copy()

print("Copy created successfully!")

Copy created successfully!

In [17]:
# Remove leading and trailing spaces from text columns
text_columns = cleaned_data.select_dtypes(include="object").columns
for column in text_columns:
    cleaned_data[column] = cleaned_data[column].str.strip()

print("Extra spaces removed successfully!")

Extra spaces removed successfully!

In [18]:
# Standardize column names

cleaned_data.columns = (
    cleaned_data.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print("Updated Column Names:")
print(cleaned_data.columns)

Updated Column Names:
Index(['order_id', 'customer_id', 'category', 'item', 'price', 'quantity',
       'order_total', 'order_date', 'payment_method'],
      dtype='object')

In [19]:
# Check missing values before handling them

print(cleaned_data.isnull().sum())

order_id             0
customer_id          0
category             0
item              1758
price              876
quantity           430
order_total        430
order_date           0
payment_method    1082
dtype: int64

In [20]:
# Fill numerical missing values with median
numeric_columns = cleaned_data.select_dtypes(include=np.number).columns
for column in numeric_columns:
    cleaned_data[column] = cleaned_data[column].fillna(
        cleaned_data[column].median()
    )

In [21]:
# Fill missing categorical/text values

categorical_columns = cleaned_data.select_dtypes(
    include="object"
).columns

for column in categorical_columns:
    cleaned_data[column] = cleaned_data[column].fillna("Unknown")

print("Missing categorical values handled!")

Missing categorical values handled!

In [22]:
# Remove duplicate records

before_duplicates = len(cleaned_data)

cleaned_data = cleaned_data.drop_duplicates()

after_duplicates = len(cleaned_data)

print("Rows before removing duplicates:", before_duplicates)
print("Rows after removing duplicates:", after_duplicates)
print("Duplicates removed:", before_duplicates - after_duplicates)

Rows before removing duplicates: 17534
Rows after removing duplicates: 17534
Duplicates removed: 0

## Prepare the data for further analysis using Pandas.

In [23]:
# Convert Price to numeric

cleaned_data["price"] = pd.to_numeric(
    cleaned_data["price"],
    errors="coerce"
)

In [24]:
# Convert Quantity to numeric

cleaned_data["quantity"] = pd.to_numeric(
    cleaned_data["quantity"],
    errors="coerce"
)

In [25]:
# Convert Quantity to integer

cleaned_data["quantity"] = cleaned_data["quantity"].round().astype("int64")

In [26]:
# Convert Order Total to numeric

cleaned_data["order_total"] = pd.to_numeric(
    cleaned_data["order_total"],
    errors="coerce"
)

# Fill missing values

cleaned_data["order_total"] = cleaned_data["order_total"].fillna(
    cleaned_data["order_total"].median()
)

In [27]:
# Standardize Category values

cleaned_data["category"] = (
    cleaned_data["category"]
    .str.strip()
    .str.title()
)

print(cleaned_data["category"].value_counts())

category
Main Dishes    3551
Starters       3527
Desserts       3496
Drinks         3488
Side Dishes    3472
Name: count, dtype: int64

In [28]:
# Standardize Payment Method values

cleaned_data["payment_method"] = (
    cleaned_data["payment_method"]
    .str.strip()
    .str.title()
)

print(cleaned_data["payment_method"].value_counts())

payment_method
Credit Card       5504
Cash              5499
Digital Wallet    5449
Unknown           1082
Name: count, dtype: int64

In [29]:
# Check missing values after cleaning

print("Missing Values After Cleaning:")
print(cleaned_data.isnull().sum())

Missing Values After Cleaning:
order_id          0
customer_id       0
category          0
item              0
price             0
quantity          0
order_total       0
order_date        0
payment_method    0
dtype: int64

In [30]:
# Check duplicates after cleaning

print(
    "Duplicate records after cleaning:",
    cleaned_data.duplicated().sum()
)

Duplicate records after cleaning: 0

In [31]:
# Check final data types

print("Final Data Types:")
print(cleaned_data.dtypes)

Final Data Types:
order_id           object
customer_id        object
category           object
item               object
price             float64
quantity            int64
order_total       float64
order_date         object
payment_method     object
dtype: object

In [32]:
# Final dataset information

cleaned_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17534 entries, 0 to 17533
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        17534 non-null  object
 1   customer_id     17534 non-null  object
 2   category        17534 non-null  object
 3   item            17534 non-null  object
 4   price           17534 non-null  float64
 5   quantity        17534 non-null  int64
 6   order_total     17534 non-null  float64
 7   order_date      17534 non-null  object
 8   payment_method  17534 non-null  object
dtypes: float64(2), int64(1), object(6)
memory usage: 1.2+ MB

In [33]:
# Final dataset shape

print("Original Dataset Shape:", data.shape)
print("Cleaned Dataset Shape:", cleaned_data.shape)

Original Dataset Shape: (17534, 9)
Cleaned Dataset Shape: (17534, 9)

In [34]:
# Display cleaned dataset

cleaned_data.head(10)

,order_id,customer_id,category,item,price,quantity,order_total,order_date,payment_method
0,ORD_705844,CUST_092,Side Dishes,Side Salad,3.0,1,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4,60.0,2023-09-27,Credit Card
3,ORD_630508,CUST_075,Drinks,Unknown,5.0,2,5.0,2022-08-09,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4,48.0,2022-05-15,Cash
5,ORD_381680,CUST_031,Main Dishes,Salmon,18.0,5,90.0,2022-07-20,Digital Wallet
6,ORD_270994,CUST_071,Side Dishes,Garlic Bread,4.0,5,20.0,2022-08-19,Credit Card
7,ORD_146656,CUST_077,Main Dishes,Unknown,15.0,3,45.0,2023-02-15,Cash
8,ORD_428611,CUST_083,Desserts,Unknown,6.0,2,12.0,2023-12-16,Cash
9,ORD_743636,CUST_085,Main Dishes,Vegetarian Platter,14.0,5,70.0,2022-08-07,Unknown

## Bonus: Save the cleaned dataset as a new CSV file.

In [35]:
# Save cleaned dataset

output_path = "../data/processed/restaurant_sales_data_cleaned.csv"

cleaned_data.to_csv(
    output_path,
    index=False
)

print("Cleaned dataset saved successfully!")
print("File:", output_path)

Cleaned dataset saved successfully!
File: ../data/processed/restaurant_sales_data_cleaned.csv